/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessControlRequestForUser {
    /// Email address for the user.
    #[serde(rename = "user_name", skip_serializing_if = "Option::is_none")]
    pub user_name: Option<String>,
    #[serde(rename = "permission_level", skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<Box<crate::models::PermissionLevel>>,
}

impl AccessControlRequestForUser {
    pub fn new() -> AccessControlRequestForUser {
        AccessControlRequestForUser {
            user_name: None,
            permission_level: None,
        }
    }
}


