/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessControlRequestForServicePrincipal {
    /// Name of an Azure service principal.
    #[serde(rename = "service_principal_name", skip_serializing_if = "Option::is_none")]
    pub service_principal_name: Option<String>,
    #[serde(rename = "permission_level", skip_serializing_if = "Option::is_none")]
    pub permission_level: Option<Box<crate::models::PermissionLevel>>,
}

impl AccessControlRequestForServicePrincipal {
    pub fn new() -> AccessControlRequestForServicePrincipal {
        AccessControlRequestForServicePrincipal {
            service_principal_name: None,
            permission_level: None,
        }
    }
}


