/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessControlList {
    /// List of permissions to set on the job.
    #[serde(rename = "access_control_list", skip_serializing_if = "Option::is_none")]
    pub access_control_list: Option<Vec<crate::models::AccessControlRequest>>,
}

impl AccessControlList {
    pub fn new() -> AccessControlList {
        AccessControlList {
            access_control_list: None,
        }
    }
}


