/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AutoScale {
    /// The minimum number of workers to which the cluster can scale down when underutilized. It is also the initial number of workers the cluster has after creation.
    #[serde(rename = "min_workers", skip_serializing_if = "Option::is_none")]
    pub min_workers: Option<i32>,
    /// The maximum number of workers to which the cluster can scale up when overloaded. max_workers must be strictly greater than min_workers.
    #[serde(rename = "max_workers", skip_serializing_if = "Option::is_none")]
    pub max_workers: Option<i32>,
}

impl AutoScale {
    pub fn new() -> AutoScale {
        AutoScale {
            min_workers: None,
            max_workers: None,
        }
    }
}


