/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AzureAttributes {
    /// The first `first_on_demand` nodes of the cluster are placed on on-demand instances. This value must be greater than 0, or else cluster creation validation fails. If this value is greater than or equal to the current cluster size, all nodes are placed on on-demand instances. If this value is less than the current cluster size, `first_on_demand` nodes are placed on on-demand instances and the remainder are placed on availability instances. This value does not affect cluster size and cannot be mutated over the lifetime of a cluster.
    #[serde(rename = "first_on_demand", skip_serializing_if = "Option::is_none")]
    pub first_on_demand: Option<i32>,
    /// Availability type used for all subsequent nodes past the `first_on_demand` ones.  `SPOT_AZURE`: use spot instances. `ON_DEMAND_AZURE`: use on demand instances. `SPOT_WITH_FALLBACK_AZURE`: preferably use spot instances, but fall back to on-demand instances if spot instances cannot be acquired (for example, if Azure spot prices are too high or out of quota). Does not apply to pool availability.
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<Availability>,
    /// The max bid price used for Azure spot instances. You can set this to greater than or equal to the current spot price. You can also set this to -1 (the default), which specifies that the instance cannot be evicted on the basis of price. The price for the instance is the current price for spot instances or the price for a standard instance. You can view historical pricing and eviction rates in the Azure portal.
    #[serde(rename = "spot_bid_max_price", skip_serializing_if = "Option::is_none")]
    pub spot_bid_max_price: Option<f64>,
}

impl AzureAttributes {
    pub fn new() -> AzureAttributes {
        AzureAttributes {
            first_on_demand: None,
            availability: None,
            spot_bid_max_price: None,
        }
    }
}

/// Availability type used for all subsequent nodes past the `first_on_demand` ones.  `SPOT_AZURE`: use spot instances. `ON_DEMAND_AZURE`: use on demand instances. `SPOT_WITH_FALLBACK_AZURE`: preferably use spot instances, but fall back to on-demand instances if spot instances cannot be acquired (for example, if Azure spot prices are too high or out of quota). Does not apply to pool availability.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Availability {
    #[serde(rename = "SPOT_AZURE")]
    SPOTAZURE,
    #[serde(rename = "ON_DEMAND_AZURE")]
    ONDEMANDAZURE,
    #[serde(rename = "SPOT_WITH_FALLBACK_AZURE")]
    SPOTWITHFALLBACKAZURE,
}

impl Default for Availability {
    fn default() -> Availability {
        Self::SPOTAZURE
    }
}

