/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CanManageRun : Permission to run and/or manage runs for the job.

/// Permission to run and/or manage runs for the job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CanManageRun {
    #[serde(rename = "CAN_MANAGE_RUN")]
    CANMANAGERUN,

}

impl ToString for CanManageRun {
    fn to_string(&self) -> String {
        match self {
            Self::CANMANAGERUN => String::from("CAN_MANAGE_RUN"),
        }
    }
}

impl Default for CanManageRun {
    fn default() -> CanManageRun {
        Self::CANMANAGERUN
    }
}




