/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CanManage : Permission to manage the job.

/// Permission to manage the job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CanManage {
    #[serde(rename = "CAN_MANAGE")]
    CANMANAGE,

}

impl ToString for CanManage {
    fn to_string(&self) -> String {
        match self {
            Self::CANMANAGE => String::from("CAN_MANAGE"),
        }
    }
}

impl Default for CanManage {
    fn default() -> CanManage {
        Self::CANMANAGE
    }
}




