/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CanView : Permission to view the settings of the job.

/// Permission to view the settings of the job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CanView {
    #[serde(rename = "CAN_VIEW")]
    CANVIEW,

}

impl ToString for CanView {
    fn to_string(&self) -> String {
        match self {
            Self::CANVIEW => String::from("CAN_VIEW"),
        }
    }
}

impl Default for CanView {
    fn default() -> CanView {
        Self::CANVIEW
    }
}




