/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ClusterCloudProviderNodeStatus : * NotEnabledOnSubscription: Node type not available for subscription. * NotAvailableInRegion: Node type not available in region. 

/// * NotEnabledOnSubscription: Node type not available for subscription. * NotAvailableInRegion: Node type not available in region. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClusterCloudProviderNodeStatus {
    #[serde(rename = "NotEnabledOnSubscription")]
    NotEnabledOnSubscription,
    #[serde(rename = "NotAvailableInRegion")]
    NotAvailableInRegion,

}

impl ToString for ClusterCloudProviderNodeStatus {
    fn to_string(&self) -> String {
        match self {
            Self::NotEnabledOnSubscription => String::from("NotEnabledOnSubscription"),
            Self::NotAvailableInRegion => String::from("NotAvailableInRegion"),
        }
    }
}

impl Default for ClusterCloudProviderNodeStatus {
    fn default() -> ClusterCloudProviderNodeStatus {
        Self::NotEnabledOnSubscription
    }
}




