/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ClusterSource : * UI: Cluster created through the UI. * JOB: Cluster created by the Databricks job scheduler. * API: Cluster created through an API call. 

/// * UI: Cluster created through the UI. * JOB: Cluster created by the Databricks job scheduler. * API: Cluster created through an API call. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ClusterSource {
    #[serde(rename = "UI")]
    UI,
    #[serde(rename = "JOB")]
    JOB,
    #[serde(rename = "API")]
    API,

}

impl ToString for ClusterSource {
    fn to_string(&self) -> String {
        match self {
            Self::UI => String::from("UI"),
            Self::JOB => String::from("JOB"),
            Self::API => String::from("API"),
        }
    }
}

impl Default for ClusterSource {
    fn default() -> ClusterSource {
        Self::UI
    }
}




