/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ClusterEvent {
    /// Canonical identifier for the cluster. This field is required.
    #[serde(rename = "cluster_id")]
    pub cluster_id: String,
    /// The timestamp when the event occurred, stored as the number of milliseconds since the unix epoch. Assigned by the Timeline service.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<i64>,
    #[serde(rename = "type")]
    pub _type: crate::models::ClusterEventType,
    #[serde(rename = "details")]
    pub details: Box<crate::models::EventDetails>,
}

impl ClusterEvent {
    pub fn new(cluster_id: String, _type: crate::models::ClusterEventType, details: crate::models::EventDetails) -> ClusterEvent {
        ClusterEvent {
            cluster_id,
            timestamp: None,
            _type,
            details: Box::new(details),
        }
    }
}


