/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DockerImage {
    /// URL for the Docker image.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "basic_auth", skip_serializing_if = "Option::is_none")]
    pub basic_auth: Option<Box<crate::models::DockerBasicAuth>>,
}

impl DockerImage {
    pub fn new() -> DockerImage {
        DockerImage {
            url: None,
            basic_auth: None,
        }
    }
}


