/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EventDetails {
    /// The number of nodes in the cluster.
    #[serde(rename = "current_num_workers", skip_serializing_if = "Option::is_none")]
    pub current_num_workers: Option<i32>,
    /// The targeted number of nodes in the cluster.
    #[serde(rename = "target_num_workers", skip_serializing_if = "Option::is_none")]
    pub target_num_workers: Option<i32>,
    #[serde(rename = "previous_attributes", skip_serializing_if = "Option::is_none")]
    pub previous_attributes: Option<Box<crate::models::AzureAttributes>>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<crate::models::AzureAttributes>>,
    #[serde(rename = "previous_cluster_size", skip_serializing_if = "Option::is_none")]
    pub previous_cluster_size: Option<Box<crate::models::ClusterSize>>,
    #[serde(rename = "cluster_size", skip_serializing_if = "Option::is_none")]
    pub cluster_size: Option<Box<crate::models::ClusterSize>>,
    #[serde(rename = "cause", skip_serializing_if = "Option::is_none")]
    pub cause: Option<crate::models::ResizeCause>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Box<crate::models::TerminationReason>>,
    /// The user that caused the event to occur. (Empty if it was done by Azure Databricks.)
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}

impl EventDetails {
    pub fn new() -> EventDetails {
        EventDetails {
            current_num_workers: None,
            target_num_workers: None,
            previous_attributes: None,
            attributes: None,
            previous_cluster_size: None,
            cluster_size: None,
            cause: None,
            reason: None,
            user: None,
        }
    }
}


