/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct FileStorageInfo {
    /// File destination. Example: `file:/my/file.sh`
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<String>,
}

impl FileStorageInfo {
    pub fn new() -> FileStorageInfo {
        FileStorageInfo {
            destination: None,
        }
    }
}


