/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2008 {
    /// The ID of the repair.
    #[serde(rename = "repair_id", skip_serializing_if = "Option::is_none")]
    pub repair_id: Option<i64>,
}

impl InlineResponse2008 {
    pub fn new() -> InlineResponse2008 {
        InlineResponse2008 {
            repair_id: None,
        }
    }
}


