/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2004 {
    /// The canonical identifier for the newly submitted run.
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<i64>,
}

impl InlineResponse2004 {
    pub fn new() -> InlineResponse2004 {
        InlineResponse2004 {
            run_id: None,
        }
    }
}


