/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2003 {
    /// The globally unique ID of the newly triggered run.
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<i64>,
    /// A unique identifier for this job run. This is set to the same value as `run_id`.
    #[serde(rename = "number_in_job", skip_serializing_if = "Option::is_none")]
    pub number_in_job: Option<i64>,
}

impl InlineResponse2003 {
    pub fn new() -> InlineResponse2003 {
        InlineResponse2003 {
            run_id: None,
            number_in_job: None,
        }
    }
}


