/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    /// A list of runs, from most recently started to least.
    #[serde(rename = "runs", skip_serializing_if = "Option::is_none")]
    pub runs: Option<Vec<crate::models::Run>>,
    /// If true, additional runs matching the provided filter are available for listing.
    #[serde(rename = "has_more", skip_serializing_if = "Option::is_none")]
    pub has_more: Option<bool>,
}

impl InlineResponse2005 {
    pub fn new() -> InlineResponse2005 {
        InlineResponse2005 {
            runs: None,
            has_more: None,
        }
    }
}


