/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject4 {
    /// The canonical identifier of the run for which to retrieve the metadata.
    #[serde(rename = "run_id", skip_serializing_if = "Option::is_none")]
    pub run_id: Option<i64>,
}

impl InlineObject4 {
    pub fn new() -> InlineObject4 {
        InlineObject4 {
            run_id: None,
        }
    }
}


