/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse2007 {
    #[serde(rename = "notebook_output", skip_serializing_if = "Option::is_none")]
    pub notebook_output: Option<Box<crate::models::NotebookOutput>>,
    /// The output from tasks that write to cluster logs such as [SparkJarTask](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#/components/schemas/SparkJarTask) or [SparkPythonTask](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#/components/schemas/SparkPythonTask. Azure Databricks restricts this API to return the last 5 MB of these logs. To return a larger result, use the [ClusterLogConf](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/clusters#clusterlogconf) field to configure log storage for the job cluster.
    #[serde(rename = "logs", skip_serializing_if = "Option::is_none")]
    pub logs: Option<String>,
    /// Whether the logs are truncated.
    #[serde(rename = "logs_truncated", skip_serializing_if = "Option::is_none")]
    pub logs_truncated: Option<bool>,
    /// An error message indicating why a task failed or why output is not available. The message is unstructured, and its exact format is subject to change.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// If there was an error executing the run, this field contains any available stack traces.
    #[serde(rename = "error_trace", skip_serializing_if = "Option::is_none")]
    pub error_trace: Option<String>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Box<crate::models::Run>>,
}

impl InlineResponse2007 {
    pub fn new() -> InlineResponse2007 {
        InlineResponse2007 {
            notebook_output: None,
            logs: None,
            logs_truncated: None,
            error: None,
            error_trace: None,
            metadata: None,
        }
    }
}


