/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineObject {
    /// The canonical identifier of the job to reset. This field is required.
    #[serde(rename = "job_id")]
    pub job_id: i64,
    #[serde(rename = "new_settings", skip_serializing_if = "Option::is_none")]
    pub new_settings: Option<Box<crate::models::JobSettings>>,
}

impl InlineObject {
    pub fn new(job_id: i64) -> InlineObject {
        InlineObject {
            job_id,
            new_settings: None,
        }
    }
}


