/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IsOwner : Perimssion that represents ownership of the job.

/// Perimssion that represents ownership of the job.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IsOwner {
    #[serde(rename = "IS_OWNER")]
    ISOWNER,

}

impl ToString for IsOwner {
    fn to_string(&self) -> String {
        match self {
            Self::ISOWNER => String::from("IS_OWNER"),
        }
    }
}

impl Default for IsOwner {
    fn default() -> IsOwner {
        Self::ISOWNER
    }
}




