/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JobCluster {
    /// A unique name for the job cluster. This field is required and must be unique within the job. `JobTaskSettings` may refer to this field to determine which cluster to launch for the task execution.
    #[serde(rename = "job_cluster_key")]
    pub job_cluster_key: String,
    #[serde(rename = "new_cluster", skip_serializing_if = "Option::is_none")]
    pub new_cluster: Option<Box<crate::models::NewCluster>>,
}

impl JobCluster {
    pub fn new(job_cluster_key: String) -> JobCluster {
        JobCluster {
            job_cluster_key,
            new_cluster: None,
        }
    }
}


