/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Library {
    /// If jar, URI of the JAR to be installed. DBFS and ADLS (`abfss`) URIs are supported. For example: `{ \"jar\": \"dbfs:/mnt/databricks/library.jar\" }` or `{ \"jar\": \"abfss://my-bucket/library.jar\" }`. If ADLS is used, make sure the cluster has read access on the library.
    #[serde(rename = "jar", skip_serializing_if = "Option::is_none")]
    pub jar: Option<String>,
    /// If egg, URI of the egg to be installed. DBFS and ADLS URIs are supported. For example: `{ \"egg\": \"dbfs:/my/egg\" }` or `{ \"egg\": \"abfss://my-bucket/egg\" }`.
    #[serde(rename = "egg", skip_serializing_if = "Option::is_none")]
    pub egg: Option<String>,
    /// If whl, URI of the wheel or zipped wheels to be installed. DBFS and ADLS URIs are supported. For example: `{ \"whl\": \"dbfs:/my/whl\" }` or `{ \"whl\": \"abfss://my-bucket/whl\" }`. If ADLS is used, make sure the cluster has read access on the library. Also the wheel file name needs to use the [correct convention](https://www.python.org/dev/peps/pep-0427/#file-format). If zipped wheels are to be installed, the file name suffix should be `.wheelhouse.zip`.
    #[serde(rename = "whl", skip_serializing_if = "Option::is_none")]
    pub whl: Option<String>,
    #[serde(rename = "pypi", skip_serializing_if = "Option::is_none")]
    pub pypi: Option<Box<crate::models::PythonPyPiLibrary>>,
    #[serde(rename = "maven", skip_serializing_if = "Option::is_none")]
    pub maven: Option<Box<crate::models::MavenLibrary>>,
    #[serde(rename = "cran", skip_serializing_if = "Option::is_none")]
    pub cran: Option<Box<crate::models::RCranLibrary>>,
}

impl Library {
    pub fn new() -> Library {
        Library {
            jar: None,
            egg: None,
            whl: None,
            pypi: None,
            maven: None,
            cran: None,
        }
    }
}


