/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PermissionLevelForGroup : Permission level to grant.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PermissionLevelForGroup {
}

impl PermissionLevelForGroup {
    /// Permission level to grant.
    pub fn new() -> PermissionLevelForGroup {
        PermissionLevelForGroup {
        }
    }
}


