/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PermissionLevel : Permission level to grant.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PermissionLevel {
}

impl PermissionLevel {
    /// Permission level to grant.
    pub fn new() -> PermissionLevel {
        PermissionLevel {
        }
    }
}


