/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PoolClusterTerminationCode : * INSTANCE_POOL_MAX_CAPACITY_FAILURE: The pool max capacity has been reached. * INSTANCE_POOL_NOT_FOUND_FAILURE: The pool specified by the cluster is no longer active or doesn’t exist.

/// * INSTANCE_POOL_MAX_CAPACITY_FAILURE: The pool max capacity has been reached. * INSTANCE_POOL_NOT_FOUND_FAILURE: The pool specified by the cluster is no longer active or doesn’t exist.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PoolClusterTerminationCode {
    #[serde(rename = "INSTANCE_POOL_MAX_CAPACITY_FAILURE")]
    MAXCAPACITYFAILURE,
    #[serde(rename = "INSTANCE_POOL_NOT_FOUND_FAILURE")]
    NOTFOUNDFAILURE,

}

impl ToString for PoolClusterTerminationCode {
    fn to_string(&self) -> String {
        match self {
            Self::MAXCAPACITYFAILURE => String::from("INSTANCE_POOL_MAX_CAPACITY_FAILURE"),
            Self::NOTFOUNDFAILURE => String::from("INSTANCE_POOL_NOT_FOUND_FAILURE"),
        }
    }
}

impl Default for PoolClusterTerminationCode {
    fn default() -> PoolClusterTerminationCode {
        Self::MAXCAPACITYFAILURE
    }
}




