/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PythonWheelTask {
    /// Name of the package to execute
    #[serde(rename = "package_name", skip_serializing_if = "Option::is_none")]
    pub package_name: Option<String>,
    /// Named entry point to use, if it does not exist in the metadata of the package it executes the function from the package directly using `$packageName.$entryPoint()`
    #[serde(rename = "entry_point", skip_serializing_if = "Option::is_none")]
    pub entry_point: Option<String>,
    /// Command-line parameters passed to python wheel task. Leave it empty if `named_parameters` is not null.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Vec<String>>,
    /// Named parameters passed to python wheel task. Leave it empty if `parameters` is not null.
    #[serde(rename = "named_parameters", skip_serializing_if = "Option::is_none")]
    pub named_parameters: Option<serde_json::Value>,
}

impl PythonWheelTask {
    pub fn new() -> PythonWheelTask {
        PythonWheelTask {
            package_name: None,
            entry_point: None,
            parameters: None,
            named_parameters: None,
        }
    }
}


