/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PythonPyPiLibrary {
    /// The name of the PyPI package to install. An optional exact version specification is also supported. Examples: `simplejson` and `simplejson==3.8.0`. This field is required.
    #[serde(rename = "package")]
    pub package: String,
    /// The repository where the package can be found. If not specified, the default pip index is used.
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
}

impl PythonPyPiLibrary {
    pub fn new(package: String) -> PythonPyPiLibrary {
        PythonPyPiLibrary {
            package,
            repo: None,
        }
    }
}


