/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RCranLibrary {
    /// The name of the CRAN package to install. This field is required.
    #[serde(rename = "package")]
    pub package: String,
    /// The repository where the package can be found. If not specified, the default CRAN repo is used.
    #[serde(rename = "repo", skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,
}

impl RCranLibrary {
    pub fn new(package: String) -> RCranLibrary {
        RCranLibrary {
            package,
            repo: None,
        }
    }
}


