/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResizeCause : * `AUTOSCALE`: Automatically resized based on load. * `USER_REQUEST`: User requested a new size. * `AUTORECOVERY`: Autorecovery monitor resized the cluster after it lost a node.

/// * `AUTOSCALE`: Automatically resized based on load. * `USER_REQUEST`: User requested a new size. * `AUTORECOVERY`: Autorecovery monitor resized the cluster after it lost a node.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResizeCause {
    #[serde(rename = "AUTOSCALE")]
    AUTOSCALE,
    #[serde(rename = "USER_REQUEST")]
    USERREQUEST,
    #[serde(rename = "AUTORECOVERY")]
    AUTORECOVERY,

}

impl ToString for ResizeCause {
    fn to_string(&self) -> String {
        match self {
            Self::AUTOSCALE => String::from("AUTOSCALE"),
            Self::USERREQUEST => String::from("USER_REQUEST"),
            Self::AUTORECOVERY => String::from("AUTORECOVERY"),
        }
    }
}

impl Default for ResizeCause {
    fn default() -> ResizeCause {
        Self::AUTOSCALE
    }
}




