/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RunType : The type of the run. * `JOB_RUN` \\- Normal job run. A run created with [Run now](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#operation/JobsRunNow).   * `WORKFLOW_RUN` \\- Workflow run. A run created with [dbutils.notebook.run](https://docs.microsoft.com/azure/databricks/dev-tools/databricks-utils#dbutils-workflow). * `SUBMIT_RUN` \\- Submit run. A run created with [Run now](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#operation/JobsRunNow).

/// The type of the run. * `JOB_RUN` \\- Normal job run. A run created with [Run now](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#operation/JobsRunNow).   * `WORKFLOW_RUN` \\- Workflow run. A run created with [dbutils.notebook.run](https://docs.microsoft.com/azure/databricks/dev-tools/databricks-utils#dbutils-workflow). * `SUBMIT_RUN` \\- Submit run. A run created with [Run now](https://docs.microsoft.com/azure/databricks/dev-tools/api/latest/jobs#operation/JobsRunNow).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RunType {
    #[serde(rename = "JOB_RUN")]
    JOBRUN,
    #[serde(rename = "WORKFLOW_RUN")]
    WORKFLOWRUN,
    #[serde(rename = "SUBMIT_RUN")]
    SUBMITRUN,

}

impl ToString for RunType {
    fn to_string(&self) -> String {
        match self {
            Self::JOBRUN => String::from("JOB_RUN"),
            Self::WORKFLOWRUN => String::from("WORKFLOW_RUN"),
            Self::SUBMITRUN => String::from("SUBMIT_RUN"),
        }
    }
}

impl Default for RunType {
    fn default() -> RunType {
        Self::JOBRUN
    }
}




