/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RunSubmitSettings {
    #[serde(rename = "tasks", skip_serializing_if = "Option::is_none")]
    pub tasks: Option<Vec<crate::models::RunSubmitTaskSettings>>,
    /// An optional name for the run. The default value is `Untitled`.
    #[serde(rename = "run_name", skip_serializing_if = "Option::is_none")]
    pub run_name: Option<String>,
    /// An optional timeout applied to each run of this job. The default behavior is to have no timeout.
    #[serde(rename = "timeout_seconds", skip_serializing_if = "Option::is_none")]
    pub timeout_seconds: Option<i32>,
    /// An optional token that can be used to guarantee the idempotency of job run requests. If a run with the provided token already exists, the request does not create a new run but returns the ID of the existing run instead.  If you specify the idempotency token, upon failure you can retry until the request succeeds. Databricks guarantees that exactly one run is launched with that idempotency token.  This token must have at most 64 characters.  For more information, see [How to ensure idempotency for jobs](https://docs.microsoft.com/azure/databricks/kb/jobs/jobs-idempotency).
    #[serde(rename = "idempotency_token", skip_serializing_if = "Option::is_none")]
    pub idempotency_token: Option<String>,
}

impl RunSubmitSettings {
    pub fn new() -> RunSubmitSettings {
        RunSubmitSettings {
            tasks: None,
            run_name: None,
            timeout_seconds: None,
            idempotency_token: None,
        }
    }
}


