/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TerminationType : * SUCCESS: Termination succeeded. * CLIENT_ERROR: Non-retriable. Client must fix parameters before reattempting the cluster creation. * SERVICE_FAULT: Databricks service issue. Client can retry. * CLOUD_FAILURECloud provider infrastructure issue. Client can retry after the underlying issue is resolved. 

/// * SUCCESS: Termination succeeded. * CLIENT_ERROR: Non-retriable. Client must fix parameters before reattempting the cluster creation. * SERVICE_FAULT: Databricks service issue. Client can retry. * CLOUD_FAILURECloud provider infrastructure issue. Client can retry after the underlying issue is resolved. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TerminationType {
    #[serde(rename = "SUCCESS")]
    SUCCESS,
    #[serde(rename = "CLIENT_ERROR")]
    CLIENTERROR,
    #[serde(rename = "SERVICE_FAULT")]
    SERVICEFAULT,
    #[serde(rename = "CLOUD_FAILURE")]
    CLOUDFAILURE,

}

impl ToString for TerminationType {
    fn to_string(&self) -> String {
        match self {
            Self::SUCCESS => String::from("SUCCESS"),
            Self::CLIENTERROR => String::from("CLIENT_ERROR"),
            Self::SERVICEFAULT => String::from("SERVICE_FAULT"),
            Self::CLOUDFAILURE => String::from("CLOUD_FAILURE"),
        }
    }
}

impl Default for TerminationType {
    fn default() -> TerminationType {
        Self::SUCCESS
    }
}




