/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TerminationReason {
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<crate::models::TerminationCode>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<crate::models::TerminationType>,
    /// An object with additional information about why a cluster was terminated. The object keys are one of `TerminationParameter` and the value is the termination information.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl TerminationReason {
    pub fn new() -> TerminationReason {
        TerminationReason {
            code: None,
            _type: None,
            parameters: None,
        }
    }
}


