/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TriggerType : * `PERIODIC`: Schedules that periodically trigger runs, such as a cron scheduler. * `ONE_TIME`: One time triggers that fire a single run. This occurs you triggered a single run on demand through the UI or the API. * `RETRY`: Indicates a run that is triggered as a retry of a previously failed run. This occurs when you request to re-run the job in case of failures.

/// * `PERIODIC`: Schedules that periodically trigger runs, such as a cron scheduler. * `ONE_TIME`: One time triggers that fire a single run. This occurs you triggered a single run on demand through the UI or the API. * `RETRY`: Indicates a run that is triggered as a retry of a previously failed run. This occurs when you request to re-run the job in case of failures.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TriggerType {
    #[serde(rename = "PERIODIC")]
    PERIODIC,
    #[serde(rename = "ONE_TIME")]
    ONETIME,
    #[serde(rename = "RETRY")]
    RETRY,

}

impl ToString for TriggerType {
    fn to_string(&self) -> String {
        match self {
            Self::PERIODIC => String::from("PERIODIC"),
            Self::ONETIME => String::from("ONE_TIME"),
            Self::RETRY => String::from("RETRY"),
        }
    }
}

impl Default for TriggerType {
    fn default() -> TriggerType {
        Self::PERIODIC
    }
}




