/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ViewsToExport : * `CODE`: Code view of the notebook. * `DASHBOARDS`: All dashboard views of the notebook. * `ALL`: All views of the notebook.

/// * `CODE`: Code view of the notebook. * `DASHBOARDS`: All dashboard views of the notebook. * `ALL`: All views of the notebook.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ViewsToExport {
    #[serde(rename = "CODE")]
    CODE,
    #[serde(rename = "DASHBOARDS")]
    DASHBOARDS,
    #[serde(rename = "ALL")]
    ALL,

}

impl ToString for ViewsToExport {
    fn to_string(&self) -> String {
        match self {
            Self::CODE => String::from("CODE"),
            Self::DASHBOARDS => String::from("DASHBOARDS"),
            Self::ALL => String::from("ALL"),
        }
    }
}

impl Default for ViewsToExport {
    fn default() -> ViewsToExport {
        Self::CODE
    }
}




