/*
 * Jobs API 2.1
 *
 * The Jobs API allows you to create, edit, and delete jobs.
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ViewType : * `NOTEBOOK`: Notebook view item. * `DASHBOARD`: Dashboard view item.

/// * `NOTEBOOK`: Notebook view item. * `DASHBOARD`: Dashboard view item.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ViewType {
    #[serde(rename = "NOTEBOOK")]
    NOTEBOOK,
    #[serde(rename = "DASHBOARD")]
    DASHBOARD,

}

impl ToString for ViewType {
    fn to_string(&self) -> String {
        match self {
            Self::NOTEBOOK => String::from("NOTEBOOK"),
            Self::DASHBOARD => String::from("DASHBOARD"),
        }
    }
}

impl Default for ViewType {
    fn default() -> ViewType {
        Self::NOTEBOOK
    }
}




